# Site settings
# in the templates available like {{ site.myvariable }}.
title: home
email: cz134@duke.edu
brand: Jiff
headline: Research Assistant
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2018 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: cz134@duke.edu
phone: not set yet

# Tracking
googleAnalitycsID: UA-83933844-1

